baseURL = 'https://example.org/'
languageCode = 'es'
title = 'Victor Rubio Fotografía'
theme = ["github.com/nicokaiser/hugo-theme-gallery/v2"]
min_version = "0.113.0"
[params]
  enableDarkMode = true
  defaultTheme = "dark"
  copyright-year = '2023'
  subtitle = 'The Best Widgets on Earth'
  [params.author]
    email = 'jsmith@example.org'
    name = 'John Smith'
[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v3"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
